export const employerDataMock = {
    "id": 3,
    "title": "Test Company",
    "picture": "",
    "bio": "Catering",
    "website": "testcompany.com",
    "response_time": 0,
    "rating": "0.0",
    "total_ratings": 0,
    "badges": [],
    "status": "APPROVED",
    "automatically_accept_from_favlists": true,
    "payroll_period_starting_time": "2022-08-22T04:00:00.000Z",
    "payroll_period_length": 7,
    "payroll_period_type": "DAYS",
    "last_payment_period": null,
    "maximum_clockin_delta_minutes": 10,
    "maximum_clockout_delay_minutes": 10,
    "created_at": "2022-08-24T14:37:43.193684Z",
    "updated_at": "2022-08-24T19:06:09.654421Z",
    "active_subscription": null,
    "payroll_configured": true,
    "uploadCompanyLogo": null,
    "editingImage": false
}