export const DummyDataWorkers = [
    { rating: 3 },
    { rating: 1 },
    { rating: 1 },
    { rating: 1 },
    { rating: 3 },
    { rating: null },
    { rating: 4 },
    { rating: 5 },
    { rating: null },
    { rating: 5 },
    { rating: 1 },
    { rating: 2 },
    { rating: 2 },
    { rating: 2 },
    { rating: 1 },
    { rating: 3 },
    { rating: 3 },
    { rating: 3 },
    { rating: 3 },
    { rating: 4 },
    { rating: 4 },
    { rating: 4 },
    { rating: 4 },
    { rating: 4 },
    { rating: 4 },
    { rating: 4 }
  ];